name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
    
    steps:
    - uses: actions/checkout@v2
      
    - name: hamer init
    env:
      TERRAFORM_WORKSPACE: hamer
      run: make init       
    - name: hamer plan
    env:
      TERRAFORM_WORKSPACE: hamer
      needs: hamer init
      run: make plan

    - name: wcplumning init
    env:
      TERRAFORM_WORKSPACE: wcplumbing
      run: make init       
    - name: wcplumbing Plan
    env:
      TERRAFORM_WORKSPACE: wcplumbing
      needs: wcplumbing init
      run: make plan
