name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      TERRAFORM_WORKSPACE: hamer
      SUBFOLDER: websites
    
    steps:
    - uses: actions/checkout@v2
      
    - name: run init
      run: make init 
      
    - name: Run check
      run: make plan
