name: Makefile CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hamerinit:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
    
    steps:
    - uses: actions/checkout@v2    
    - name: hamer init
      env:
        TERRAFORM_WORKSPACE: hamer
      run: make init       

  hamerplan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
      TERRAFORM_WORKSPACE: hamer
    
    steps:
    - uses: actions/checkout@v2    
    - name: hamer plan
      needs: hamerinit
      run: make plan

  wcplumbinginit:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
    
    steps:
    - uses: actions/checkout@v2 
    - name: wcplumning init
      env:
        TERRAFORM_WORKSPACE: wcplumbing
      run: make init       

  wcplumbingplan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
    
    steps:
    - uses: actions/checkout@v2 
    - name: wcplumbing Plan
      env:
        TERRAFORM_WORKSPACE: wcplumbing
      needs: wcplumbinginit
      run: make plan