name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: run init
      run: export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} SUBFOLDER=websites TERRAFORM_WORKSPACE=hamer make init 
      
    - name: Run check
      run: export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} SUBFOLDER=websites TERRAFORM_WORKSPACE=hamer make plan
