name: Makefile CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hamer.cloud plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
      TERRAFORM_WORKSPACE: hamer
    steps:
    - uses: actions/checkout@v2    
    - name: hamer plan
      run: make plan

  hamer.cloud apply:
    runs-on: ubuntu-latest
    needs: hamer.cloud plan
    environment: Hamer-prod
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
      TERRAFORM_WORKSPACE: hamer
    steps:
    - uses: actions/checkout@v2    
    - name: Hamer Apply
      run: make applyAuto

  wcplumbing.com.au plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
    steps:
    - uses: actions/checkout@v2 
    - name: wcplumbing Plan
      env:
        TERRAFORM_WORKSPACE: wcplumbing
      run: make plan

  wcplumbing.com.au apply:
    runs-on: ubuntu-latest
    needs: wcplumbing.com.au plan
    environment: Hamer-prod
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
    steps:
    - uses: actions/checkout@v2 
    - name: wcplumbing Apply
      env:
        TERRAFORM_WORKSPACE: wcplumbing
      run: make applyAuto

  ThomasHamer VPC plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: vpc
    steps:
    - uses: actions/checkout@v2 
    - name: VPC Plan
      env:
        TERRAFORM_WORKSPACE: prod
      run: make plan

  ThomasHamer VPC apply:
    runs-on: ubuntu-latest
    needs: ThomasHamer VPC plan
    environment: Hamer-prod
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
    steps:
    - uses: actions/checkout@v2 
    - name: wcplumbing Apply
      env:
        TERRAFORM_WORKSPACE: wcplumbing
      run: make applyAuto