name: Makefile CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hamer_cloud-plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
      TERRAFORM_WORKSPACE: hamer
    steps:
    - uses: actions/checkout@v2    
    - name: hamer plan
      run: make plan

  hamer_cloud-apply:
    runs-on: ubuntu-latest
    needs: hamer_cloud-plan
    environment: Hamer-prod
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
      TERRAFORM_WORKSPACE: hamer
    steps:
    - uses: actions/checkout@v2    
    - name: Hamer Apply
      run: make applyAuto

  wcplumbing_com_au-plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
    steps:
    - uses: actions/checkout@v2 
    - name: wcplumbing Plan
      env:
        TERRAFORM_WORKSPACE: wcplumbing
      run: make plan

  wcplumbing_com_au-apply:
    runs-on: ubuntu-latest
    needs: wcplumbing_com_au-plan
    environment: Hamer-prod
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
    steps:
    - uses: actions/checkout@v2 
    - name: wcplumbing Apply
      env:
        TERRAFORM_WORKSPACE: wcplumbing
      run: make applyAuto

  ThomasHamerVPC-plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: vpc
    steps:
    - uses: actions/checkout@v2 
    - name: VPC Plan
      env:
        TERRAFORM_WORKSPACE: prod
      run: make plan

  ThomasHamerVPC-apply:
    runs-on: ubuntu-latest
    needs: ThomasHamerVPC-plan
    environment: Hamer-prod
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
    steps:
    - uses: actions/checkout@v2 
    - name: wcplumbing Apply
      env:
        TERRAFORM_WORKSPACE: wcplumbing
      run: make applyAuto