name: Makefile CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Lint Terraform
        uses: actionshub/terraform-lint@main

  hamer_cloud-plan:
    runs-on: ubuntu-latest
    needs: lint
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
      TERRAFORM_WORKSPACE: hamer
    steps:
      - uses: actions/checkout@v4
      - name: hamer plan
        run: make plan

  hamer_cloud-apply:
    runs-on: ubuntu-latest
    needs: hamer_cloud-plan
    environment: hamercloud
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: websites
      TERRAFORM_WORKSPACE: hamer
    steps:
      - uses: actions/checkout@v4
      - name: Hamer Apply
        run: make applyAuto

  ThomasHamerVPC-plan:
    runs-on: ubuntu-latest
    needs: lint
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: vpc
    steps:
      - uses: actions/checkout@v4
      - name: VPC Plan
        env:
          TERRAFORM_WORKSPACE: prod
        run: make plan

  ThomasHamerVPC-apply:
    runs-on: ubuntu-latest
    needs: ThomasHamerVPC-plan
    environment: thomashamer_vpc
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      region: ${{secrets.AWS_REGION}}
      SUBFOLDER: vpc
    steps:
      - uses: actions/checkout@v4
      - name: ThomasHamer_VPC-Apply
        env:
          TERRAFORM_WORKSPACE: prod
        run: make applyAuto
